// Code generated by protoc-gen-go. DO NOT EDIT.
// source: example.proto

package example

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Greeting struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Greeting) Reset()         { *m = Greeting{} }
func (m *Greeting) String() string { return proto.CompactTextString(m) }
func (*Greeting) ProtoMessage()    {}
func (*Greeting) Descriptor() ([]byte, []int) {
	return fileDescriptor_15a1dc8d40dadaa6, []int{0}
}

func (m *Greeting) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Greeting.Unmarshal(m, b)
}
func (m *Greeting) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Greeting.Marshal(b, m, deterministic)
}
func (m *Greeting) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Greeting.Merge(m, src)
}
func (m *Greeting) XXX_Size() int {
	return xxx_messageInfo_Greeting.Size(m)
}
func (m *Greeting) XXX_DiscardUnknown() {
	xxx_messageInfo_Greeting.DiscardUnknown(m)
}

var xxx_messageInfo_Greeting proto.InternalMessageInfo

func (m *Greeting) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type Acknowledgement struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Acknowledgement) Reset()         { *m = Acknowledgement{} }
func (m *Acknowledgement) String() string { return proto.CompactTextString(m) }
func (*Acknowledgement) ProtoMessage()    {}
func (*Acknowledgement) Descriptor() ([]byte, []int) {
	return fileDescriptor_15a1dc8d40dadaa6, []int{1}
}

func (m *Acknowledgement) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Acknowledgement.Unmarshal(m, b)
}
func (m *Acknowledgement) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Acknowledgement.Marshal(b, m, deterministic)
}
func (m *Acknowledgement) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Acknowledgement.Merge(m, src)
}
func (m *Acknowledgement) XXX_Size() int {
	return xxx_messageInfo_Acknowledgement.Size(m)
}
func (m *Acknowledgement) XXX_DiscardUnknown() {
	xxx_messageInfo_Acknowledgement.DiscardUnknown(m)
}

var xxx_messageInfo_Acknowledgement proto.InternalMessageInfo

func (m *Acknowledgement) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_15a1dc8d40dadaa6, []int{2}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

type Credentials struct {
	ApiKey               string   `protobuf:"bytes,1,opt,name=apiKey,proto3" json:"apiKey,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Credentials) Reset()         { *m = Credentials{} }
func (m *Credentials) String() string { return proto.CompactTextString(m) }
func (*Credentials) ProtoMessage()    {}
func (*Credentials) Descriptor() ([]byte, []int) {
	return fileDescriptor_15a1dc8d40dadaa6, []int{3}
}

func (m *Credentials) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Credentials.Unmarshal(m, b)
}
func (m *Credentials) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Credentials.Marshal(b, m, deterministic)
}
func (m *Credentials) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Credentials.Merge(m, src)
}
func (m *Credentials) XXX_Size() int {
	return xxx_messageInfo_Credentials.Size(m)
}
func (m *Credentials) XXX_DiscardUnknown() {
	xxx_messageInfo_Credentials.DiscardUnknown(m)
}

var xxx_messageInfo_Credentials proto.InternalMessageInfo

func (m *Credentials) GetApiKey() string {
	if m != nil {
		return m.ApiKey
	}
	return ""
}

type AccessToken struct {
	Jwt                  string   `protobuf:"bytes,1,opt,name=jwt,proto3" json:"jwt,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AccessToken) Reset()         { *m = AccessToken{} }
func (m *AccessToken) String() string { return proto.CompactTextString(m) }
func (*AccessToken) ProtoMessage()    {}
func (*AccessToken) Descriptor() ([]byte, []int) {
	return fileDescriptor_15a1dc8d40dadaa6, []int{4}
}

func (m *AccessToken) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccessToken.Unmarshal(m, b)
}
func (m *AccessToken) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccessToken.Marshal(b, m, deterministic)
}
func (m *AccessToken) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccessToken.Merge(m, src)
}
func (m *AccessToken) XXX_Size() int {
	return xxx_messageInfo_AccessToken.Size(m)
}
func (m *AccessToken) XXX_DiscardUnknown() {
	xxx_messageInfo_AccessToken.DiscardUnknown(m)
}

var xxx_messageInfo_AccessToken proto.InternalMessageInfo

func (m *AccessToken) GetJwt() string {
	if m != nil {
		return m.Jwt
	}
	return ""
}

type GreetCommand struct {
	AggregateIdentifier  string    `protobuf:"bytes,1,opt,name=aggregateIdentifier,proto3" json:"aggregateIdentifier,omitempty"`
	Message              *Greeting `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *GreetCommand) Reset()         { *m = GreetCommand{} }
func (m *GreetCommand) String() string { return proto.CompactTextString(m) }
func (*GreetCommand) ProtoMessage()    {}
func (*GreetCommand) Descriptor() ([]byte, []int) {
	return fileDescriptor_15a1dc8d40dadaa6, []int{5}
}

func (m *GreetCommand) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GreetCommand.Unmarshal(m, b)
}
func (m *GreetCommand) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GreetCommand.Marshal(b, m, deterministic)
}
func (m *GreetCommand) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GreetCommand.Merge(m, src)
}
func (m *GreetCommand) XXX_Size() int {
	return xxx_messageInfo_GreetCommand.Size(m)
}
func (m *GreetCommand) XXX_DiscardUnknown() {
	xxx_messageInfo_GreetCommand.DiscardUnknown(m)
}

var xxx_messageInfo_GreetCommand proto.InternalMessageInfo

func (m *GreetCommand) GetAggregateIdentifier() string {
	if m != nil {
		return m.AggregateIdentifier
	}
	return ""
}

func (m *GreetCommand) GetMessage() *Greeting {
	if m != nil {
		return m.Message
	}
	return nil
}

type RecordCommand struct {
	AggregateIdentifier  string   `protobuf:"bytes,1,opt,name=aggregateIdentifier,proto3" json:"aggregateIdentifier,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RecordCommand) Reset()         { *m = RecordCommand{} }
func (m *RecordCommand) String() string { return proto.CompactTextString(m) }
func (*RecordCommand) ProtoMessage()    {}
func (*RecordCommand) Descriptor() ([]byte, []int) {
	return fileDescriptor_15a1dc8d40dadaa6, []int{6}
}

func (m *RecordCommand) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RecordCommand.Unmarshal(m, b)
}
func (m *RecordCommand) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RecordCommand.Marshal(b, m, deterministic)
}
func (m *RecordCommand) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RecordCommand.Merge(m, src)
}
func (m *RecordCommand) XXX_Size() int {
	return xxx_messageInfo_RecordCommand.Size(m)
}
func (m *RecordCommand) XXX_DiscardUnknown() {
	xxx_messageInfo_RecordCommand.DiscardUnknown(m)
}

var xxx_messageInfo_RecordCommand proto.InternalMessageInfo

func (m *RecordCommand) GetAggregateIdentifier() string {
	if m != nil {
		return m.AggregateIdentifier
	}
	return ""
}

type StopCommand struct {
	AggregateIdentifier  string   `protobuf:"bytes,1,opt,name=aggregateIdentifier,proto3" json:"aggregateIdentifier,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StopCommand) Reset()         { *m = StopCommand{} }
func (m *StopCommand) String() string { return proto.CompactTextString(m) }
func (*StopCommand) ProtoMessage()    {}
func (*StopCommand) Descriptor() ([]byte, []int) {
	return fileDescriptor_15a1dc8d40dadaa6, []int{7}
}

func (m *StopCommand) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StopCommand.Unmarshal(m, b)
}
func (m *StopCommand) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StopCommand.Marshal(b, m, deterministic)
}
func (m *StopCommand) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StopCommand.Merge(m, src)
}
func (m *StopCommand) XXX_Size() int {
	return xxx_messageInfo_StopCommand.Size(m)
}
func (m *StopCommand) XXX_DiscardUnknown() {
	xxx_messageInfo_StopCommand.DiscardUnknown(m)
}

var xxx_messageInfo_StopCommand proto.InternalMessageInfo

func (m *StopCommand) GetAggregateIdentifier() string {
	if m != nil {
		return m.AggregateIdentifier
	}
	return ""
}

type GreetedEvent struct {
	Message              *Greeting `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *GreetedEvent) Reset()         { *m = GreetedEvent{} }
func (m *GreetedEvent) String() string { return proto.CompactTextString(m) }
func (*GreetedEvent) ProtoMessage()    {}
func (*GreetedEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_15a1dc8d40dadaa6, []int{8}
}

func (m *GreetedEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GreetedEvent.Unmarshal(m, b)
}
func (m *GreetedEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GreetedEvent.Marshal(b, m, deterministic)
}
func (m *GreetedEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GreetedEvent.Merge(m, src)
}
func (m *GreetedEvent) XXX_Size() int {
	return xxx_messageInfo_GreetedEvent.Size(m)
}
func (m *GreetedEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_GreetedEvent.DiscardUnknown(m)
}

var xxx_messageInfo_GreetedEvent proto.InternalMessageInfo

func (m *GreetedEvent) GetMessage() *Greeting {
	if m != nil {
		return m.Message
	}
	return nil
}

type StartedRecordingEvent struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StartedRecordingEvent) Reset()         { *m = StartedRecordingEvent{} }
func (m *StartedRecordingEvent) String() string { return proto.CompactTextString(m) }
func (*StartedRecordingEvent) ProtoMessage()    {}
func (*StartedRecordingEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_15a1dc8d40dadaa6, []int{9}
}

func (m *StartedRecordingEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StartedRecordingEvent.Unmarshal(m, b)
}
func (m *StartedRecordingEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StartedRecordingEvent.Marshal(b, m, deterministic)
}
func (m *StartedRecordingEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StartedRecordingEvent.Merge(m, src)
}
func (m *StartedRecordingEvent) XXX_Size() int {
	return xxx_messageInfo_StartedRecordingEvent.Size(m)
}
func (m *StartedRecordingEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_StartedRecordingEvent.DiscardUnknown(m)
}

var xxx_messageInfo_StartedRecordingEvent proto.InternalMessageInfo

type StoppedRecordingEvent struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StoppedRecordingEvent) Reset()         { *m = StoppedRecordingEvent{} }
func (m *StoppedRecordingEvent) String() string { return proto.CompactTextString(m) }
func (*StoppedRecordingEvent) ProtoMessage()    {}
func (*StoppedRecordingEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_15a1dc8d40dadaa6, []int{10}
}

func (m *StoppedRecordingEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StoppedRecordingEvent.Unmarshal(m, b)
}
func (m *StoppedRecordingEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StoppedRecordingEvent.Marshal(b, m, deterministic)
}
func (m *StoppedRecordingEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StoppedRecordingEvent.Merge(m, src)
}
func (m *StoppedRecordingEvent) XXX_Size() int {
	return xxx_messageInfo_StoppedRecordingEvent.Size(m)
}
func (m *StoppedRecordingEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_StoppedRecordingEvent.DiscardUnknown(m)
}

var xxx_messageInfo_StoppedRecordingEvent proto.InternalMessageInfo

type SearchQuery struct {
	Query                string   `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SearchQuery) Reset()         { *m = SearchQuery{} }
func (m *SearchQuery) String() string { return proto.CompactTextString(m) }
func (*SearchQuery) ProtoMessage()    {}
func (*SearchQuery) Descriptor() ([]byte, []int) {
	return fileDescriptor_15a1dc8d40dadaa6, []int{11}
}

func (m *SearchQuery) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchQuery.Unmarshal(m, b)
}
func (m *SearchQuery) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchQuery.Marshal(b, m, deterministic)
}
func (m *SearchQuery) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchQuery.Merge(m, src)
}
func (m *SearchQuery) XXX_Size() int {
	return xxx_messageInfo_SearchQuery.Size(m)
}
func (m *SearchQuery) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchQuery.DiscardUnknown(m)
}

var xxx_messageInfo_SearchQuery proto.InternalMessageInfo

func (m *SearchQuery) GetQuery() string {
	if m != nil {
		return m.Query
	}
	return ""
}

func init() {
	proto.RegisterType((*Greeting)(nil), "org.leialearns.grpc.example.Greeting")
	proto.RegisterType((*Acknowledgement)(nil), "org.leialearns.grpc.example.Acknowledgement")
	proto.RegisterType((*Empty)(nil), "org.leialearns.grpc.example.Empty")
	proto.RegisterType((*Credentials)(nil), "org.leialearns.grpc.example.Credentials")
	proto.RegisterType((*AccessToken)(nil), "org.leialearns.grpc.example.AccessToken")
	proto.RegisterType((*GreetCommand)(nil), "org.leialearns.grpc.example.GreetCommand")
	proto.RegisterType((*RecordCommand)(nil), "org.leialearns.grpc.example.RecordCommand")
	proto.RegisterType((*StopCommand)(nil), "org.leialearns.grpc.example.StopCommand")
	proto.RegisterType((*GreetedEvent)(nil), "org.leialearns.grpc.example.GreetedEvent")
	proto.RegisterType((*StartedRecordingEvent)(nil), "org.leialearns.grpc.example.StartedRecordingEvent")
	proto.RegisterType((*StoppedRecordingEvent)(nil), "org.leialearns.grpc.example.StoppedRecordingEvent")
	proto.RegisterType((*SearchQuery)(nil), "org.leialearns.grpc.example.SearchQuery")
}

func init() {
	proto.RegisterFile("example.proto", fileDescriptor_15a1dc8d40dadaa6)
}

var fileDescriptor_15a1dc8d40dadaa6 = []byte{
	// 439 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x54, 0x5d, 0x6f, 0xd3, 0x30,
	0x14, 0x6d, 0x60, 0xed, 0xe8, 0x0d, 0x03, 0x64, 0xc6, 0x98, 0xca, 0x03, 0x93, 0x61, 0x52, 0x25,
	0x50, 0x3a, 0x8d, 0x1f, 0x50, 0x95, 0x69, 0x42, 0x88, 0x07, 0xa0, 0xe5, 0x69, 0x12, 0x48, 0x26,
	0xb9, 0x78, 0xa6, 0x89, 0x6d, 0xae, 0xbd, 0x8d, 0xf2, 0xc6, 0x7f, 0xe2, 0x07, 0xa2, 0x24, 0x2e,
	0x1b, 0x1f, 0xca, 0xb2, 0x8a, 0x37, 0xdf, 0xde, 0x73, 0x4f, 0xcf, 0x3d, 0xc7, 0x0e, 0x6c, 0xe0,
	0x57, 0x51, 0xd8, 0x1c, 0x13, 0x4b, 0xc6, 0x1b, 0xf6, 0xc0, 0x90, 0x4c, 0x72, 0x54, 0x22, 0x47,
	0x41, 0xda, 0x25, 0x92, 0x6c, 0x9a, 0x04, 0x08, 0x7f, 0x0c, 0x37, 0x5e, 0x10, 0xa2, 0x57, 0x5a,
	0xb2, 0x6d, 0x58, 0x2f, 0xd0, 0x39, 0x21, 0x71, 0x3b, 0xda, 0x89, 0x86, 0xfd, 0xe9, 0xb2, 0xe4,
	0x4f, 0xe0, 0xf6, 0x24, 0x9d, 0x6b, 0x73, 0x96, 0x63, 0x26, 0xb1, 0x40, 0xed, 0x1b, 0xc0, 0xeb,
	0xd0, 0x3d, 0x2c, 0xac, 0x5f, 0xf0, 0x5d, 0x88, 0x0f, 0x08, 0x33, 0xd4, 0x5e, 0x89, 0xdc, 0xb1,
	0x2d, 0xe8, 0x09, 0xab, 0x5e, 0xe1, 0x22, 0x0c, 0x84, 0x8a, 0x3f, 0x84, 0x78, 0x92, 0xa6, 0xe8,
	0xdc, 0x3b, 0x33, 0x47, 0xcd, 0xee, 0xc0, 0xf5, 0xcf, 0x67, 0x3e, 0x60, 0xca, 0x23, 0xff, 0x1e,
	0xc1, 0xcd, 0x4a, 0xe4, 0x81, 0x29, 0x0a, 0xa1, 0x33, 0xb6, 0x07, 0x77, 0x85, 0x94, 0x84, 0x52,
	0x78, 0x7c, 0x59, 0xf1, 0x7f, 0x52, 0x48, 0x61, 0xe4, 0x5f, 0x2d, 0x36, 0x3e, 0x57, 0x7b, 0x6d,
	0x27, 0x1a, 0xc6, 0xfb, 0xbb, 0x49, 0x83, 0x2b, 0xc9, 0xd2, 0x92, 0xf3, 0xa5, 0x26, 0xb0, 0x31,
	0xc5, 0xd4, 0x50, 0xb6, 0xb2, 0x06, 0x3e, 0x86, 0x78, 0xe6, 0x8d, 0x5d, 0x9d, 0xe0, 0x75, 0xb0,
	0x01, 0xb3, 0xc3, 0xd3, 0x32, 0x82, 0xf1, 0xef, 0x11, 0x5c, 0x7d, 0xa9, 0xfb, 0x70, 0x6f, 0xe6,
	0x05, 0x79, 0xcc, 0xea, 0xdd, 0x94, 0x96, 0x15, 0x73, 0xdd, 0x30, 0xd6, 0xfe, 0xd5, 0x78, 0x04,
	0xf1, 0x0c, 0x05, 0xa5, 0xc7, 0x6f, 0x4f, 0x90, 0x16, 0x6c, 0x13, 0xba, 0x5f, 0xca, 0x43, 0x50,
	0x5d, 0x17, 0xfb, 0x3f, 0xd6, 0xe0, 0x56, 0x2d, 0x94, 0x66, 0x48, 0xa7, 0x2a, 0x45, 0xf6, 0x01,
	0xba, 0xd5, 0x2f, 0xac, 0x9d, 0xc4, 0xc1, 0xd3, 0x46, 0xd8, 0x1f, 0x77, 0x91, 0x77, 0xd8, 0x11,
	0xf4, 0x97, 0xb3, 0x8e, 0xf1, 0xc6, 0xe1, 0xea, 0x6e, 0x0e, 0xda, 0xe9, 0xe0, 0x9d, 0xbd, 0x88,
	0x4d, 0xa1, 0x57, 0xbb, 0xd0, 0x8a, 0xb8, 0x05, 0x86, 0x77, 0xd8, 0x1b, 0x58, 0x2b, 0x0d, 0xfe,
	0x8f, 0x8c, 0xef, 0xa1, 0x57, 0x27, 0xc3, 0x86, 0x8d, 0xf8, 0x0b, 0xf1, 0x5d, 0xc5, 0x04, 0x01,
	0xfd, 0xc9, 0x89, 0x3f, 0x36, 0xa4, 0xbe, 0xe1, 0x25, 0xff, 0x70, 0xe1, 0xcd, 0x0f, 0x86, 0x97,
	0xe4, 0xf8, 0xeb, 0xd9, 0xf3, 0xce, 0xf3, 0xad, 0xa3, 0x4d, 0x47, 0xe9, 0xc8, 0xce, 0xe5, 0xa8,
	0x44, 0x8d, 0x02, 0xea, 0x63, 0xaf, 0xfa, 0x8c, 0x3d, 0xfb, 0x19, 0x00, 0x00, 0xff, 0xff, 0x8f,
	0x9c, 0xfb, 0xe4, 0xd7, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// GreeterServiceClient is the client API for GreeterService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GreeterServiceClient interface {
	Greet(ctx context.Context, in *Greeting, opts ...grpc.CallOption) (*Acknowledgement, error)
	Greetings(ctx context.Context, in *Empty, opts ...grpc.CallOption) (GreeterService_GreetingsClient, error)
	Record(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error)
	Stop(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error)
	Search(ctx context.Context, in *SearchQuery, opts ...grpc.CallOption) (GreeterService_SearchClient, error)
	Authorize(ctx context.Context, in *Credentials, opts ...grpc.CallOption) (*AccessToken, error)
}

type greeterServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGreeterServiceClient(cc grpc.ClientConnInterface) GreeterServiceClient {
	return &greeterServiceClient{cc}
}

func (c *greeterServiceClient) Greet(ctx context.Context, in *Greeting, opts ...grpc.CallOption) (*Acknowledgement, error) {
	out := new(Acknowledgement)
	err := c.cc.Invoke(ctx, "/org.leialearns.grpc.example.GreeterService/Greet", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *greeterServiceClient) Greetings(ctx context.Context, in *Empty, opts ...grpc.CallOption) (GreeterService_GreetingsClient, error) {
	stream, err := c.cc.NewStream(ctx, &_GreeterService_serviceDesc.Streams[0], "/org.leialearns.grpc.example.GreeterService/Greetings", opts...)
	if err != nil {
		return nil, err
	}
	x := &greeterServiceGreetingsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type GreeterService_GreetingsClient interface {
	Recv() (*Greeting, error)
	grpc.ClientStream
}

type greeterServiceGreetingsClient struct {
	grpc.ClientStream
}

func (x *greeterServiceGreetingsClient) Recv() (*Greeting, error) {
	m := new(Greeting)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *greeterServiceClient) Record(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/org.leialearns.grpc.example.GreeterService/Record", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *greeterServiceClient) Stop(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/org.leialearns.grpc.example.GreeterService/Stop", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *greeterServiceClient) Search(ctx context.Context, in *SearchQuery, opts ...grpc.CallOption) (GreeterService_SearchClient, error) {
	stream, err := c.cc.NewStream(ctx, &_GreeterService_serviceDesc.Streams[1], "/org.leialearns.grpc.example.GreeterService/Search", opts...)
	if err != nil {
		return nil, err
	}
	x := &greeterServiceSearchClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type GreeterService_SearchClient interface {
	Recv() (*Greeting, error)
	grpc.ClientStream
}

type greeterServiceSearchClient struct {
	grpc.ClientStream
}

func (x *greeterServiceSearchClient) Recv() (*Greeting, error) {
	m := new(Greeting)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *greeterServiceClient) Authorize(ctx context.Context, in *Credentials, opts ...grpc.CallOption) (*AccessToken, error) {
	out := new(AccessToken)
	err := c.cc.Invoke(ctx, "/org.leialearns.grpc.example.GreeterService/Authorize", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GreeterServiceServer is the server API for GreeterService service.
type GreeterServiceServer interface {
	Greet(context.Context, *Greeting) (*Acknowledgement, error)
	Greetings(*Empty, GreeterService_GreetingsServer) error
	Record(context.Context, *Empty) (*Empty, error)
	Stop(context.Context, *Empty) (*Empty, error)
	Search(*SearchQuery, GreeterService_SearchServer) error
	Authorize(context.Context, *Credentials) (*AccessToken, error)
}

// UnimplementedGreeterServiceServer can be embedded to have forward compatible implementations.
type UnimplementedGreeterServiceServer struct {
}

func (*UnimplementedGreeterServiceServer) Greet(ctx context.Context, req *Greeting) (*Acknowledgement, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Greet not implemented")
}
func (*UnimplementedGreeterServiceServer) Greetings(req *Empty, srv GreeterService_GreetingsServer) error {
	return status.Errorf(codes.Unimplemented, "method Greetings not implemented")
}
func (*UnimplementedGreeterServiceServer) Record(ctx context.Context, req *Empty) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Record not implemented")
}
func (*UnimplementedGreeterServiceServer) Stop(ctx context.Context, req *Empty) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Stop not implemented")
}
func (*UnimplementedGreeterServiceServer) Search(req *SearchQuery, srv GreeterService_SearchServer) error {
	return status.Errorf(codes.Unimplemented, "method Search not implemented")
}
func (*UnimplementedGreeterServiceServer) Authorize(ctx context.Context, req *Credentials) (*AccessToken, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Authorize not implemented")
}

func RegisterGreeterServiceServer(s *grpc.Server, srv GreeterServiceServer) {
	s.RegisterService(&_GreeterService_serviceDesc, srv)
}

func _GreeterService_Greet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Greeting)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreeterServiceServer).Greet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/org.leialearns.grpc.example.GreeterService/Greet",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreeterServiceServer).Greet(ctx, req.(*Greeting))
	}
	return interceptor(ctx, in, info, handler)
}

func _GreeterService_Greetings_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(GreeterServiceServer).Greetings(m, &greeterServiceGreetingsServer{stream})
}

type GreeterService_GreetingsServer interface {
	Send(*Greeting) error
	grpc.ServerStream
}

type greeterServiceGreetingsServer struct {
	grpc.ServerStream
}

func (x *greeterServiceGreetingsServer) Send(m *Greeting) error {
	return x.ServerStream.SendMsg(m)
}

func _GreeterService_Record_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreeterServiceServer).Record(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/org.leialearns.grpc.example.GreeterService/Record",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreeterServiceServer).Record(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _GreeterService_Stop_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreeterServiceServer).Stop(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/org.leialearns.grpc.example.GreeterService/Stop",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreeterServiceServer).Stop(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _GreeterService_Search_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SearchQuery)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(GreeterServiceServer).Search(m, &greeterServiceSearchServer{stream})
}

type GreeterService_SearchServer interface {
	Send(*Greeting) error
	grpc.ServerStream
}

type greeterServiceSearchServer struct {
	grpc.ServerStream
}

func (x *greeterServiceSearchServer) Send(m *Greeting) error {
	return x.ServerStream.SendMsg(m)
}

func _GreeterService_Authorize_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Credentials)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreeterServiceServer).Authorize(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/org.leialearns.grpc.example.GreeterService/Authorize",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreeterServiceServer).Authorize(ctx, req.(*Credentials))
	}
	return interceptor(ctx, in, info, handler)
}

var _GreeterService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "org.leialearns.grpc.example.GreeterService",
	HandlerType: (*GreeterServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Greet",
			Handler:    _GreeterService_Greet_Handler,
		},
		{
			MethodName: "Record",
			Handler:    _GreeterService_Record_Handler,
		},
		{
			MethodName: "Stop",
			Handler:    _GreeterService_Stop_Handler,
		},
		{
			MethodName: "Authorize",
			Handler:    _GreeterService_Authorize_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Greetings",
			Handler:       _GreeterService_Greetings_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "Search",
			Handler:       _GreeterService_Search_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "example.proto",
}
