// Code generated by protoc-gen-go. DO NOT EDIT.
// source: example.proto

package example

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Greeting struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Greeting) Reset()         { *m = Greeting{} }
func (m *Greeting) String() string { return proto.CompactTextString(m) }
func (*Greeting) ProtoMessage()    {}
func (*Greeting) Descriptor() ([]byte, []int) {
	return fileDescriptor_15a1dc8d40dadaa6, []int{0}
}

func (m *Greeting) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Greeting.Unmarshal(m, b)
}
func (m *Greeting) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Greeting.Marshal(b, m, deterministic)
}
func (m *Greeting) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Greeting.Merge(m, src)
}
func (m *Greeting) XXX_Size() int {
	return xxx_messageInfo_Greeting.Size(m)
}
func (m *Greeting) XXX_DiscardUnknown() {
	xxx_messageInfo_Greeting.DiscardUnknown(m)
}

var xxx_messageInfo_Greeting proto.InternalMessageInfo

func (m *Greeting) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type Acknowledgement struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Acknowledgement) Reset()         { *m = Acknowledgement{} }
func (m *Acknowledgement) String() string { return proto.CompactTextString(m) }
func (*Acknowledgement) ProtoMessage()    {}
func (*Acknowledgement) Descriptor() ([]byte, []int) {
	return fileDescriptor_15a1dc8d40dadaa6, []int{1}
}

func (m *Acknowledgement) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Acknowledgement.Unmarshal(m, b)
}
func (m *Acknowledgement) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Acknowledgement.Marshal(b, m, deterministic)
}
func (m *Acknowledgement) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Acknowledgement.Merge(m, src)
}
func (m *Acknowledgement) XXX_Size() int {
	return xxx_messageInfo_Acknowledgement.Size(m)
}
func (m *Acknowledgement) XXX_DiscardUnknown() {
	xxx_messageInfo_Acknowledgement.DiscardUnknown(m)
}

var xxx_messageInfo_Acknowledgement proto.InternalMessageInfo

func (m *Acknowledgement) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type GreetCommand struct {
	AggregateIdentifier  string    `protobuf:"bytes,1,opt,name=aggregateIdentifier,proto3" json:"aggregateIdentifier,omitempty"`
	Message              *Greeting `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *GreetCommand) Reset()         { *m = GreetCommand{} }
func (m *GreetCommand) String() string { return proto.CompactTextString(m) }
func (*GreetCommand) ProtoMessage()    {}
func (*GreetCommand) Descriptor() ([]byte, []int) {
	return fileDescriptor_15a1dc8d40dadaa6, []int{2}
}

func (m *GreetCommand) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GreetCommand.Unmarshal(m, b)
}
func (m *GreetCommand) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GreetCommand.Marshal(b, m, deterministic)
}
func (m *GreetCommand) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GreetCommand.Merge(m, src)
}
func (m *GreetCommand) XXX_Size() int {
	return xxx_messageInfo_GreetCommand.Size(m)
}
func (m *GreetCommand) XXX_DiscardUnknown() {
	xxx_messageInfo_GreetCommand.DiscardUnknown(m)
}

var xxx_messageInfo_GreetCommand proto.InternalMessageInfo

func (m *GreetCommand) GetAggregateIdentifier() string {
	if m != nil {
		return m.AggregateIdentifier
	}
	return ""
}

func (m *GreetCommand) GetMessage() *Greeting {
	if m != nil {
		return m.Message
	}
	return nil
}

type GreetedEvent struct {
	Message              *Greeting `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *GreetedEvent) Reset()         { *m = GreetedEvent{} }
func (m *GreetedEvent) String() string { return proto.CompactTextString(m) }
func (*GreetedEvent) ProtoMessage()    {}
func (*GreetedEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_15a1dc8d40dadaa6, []int{3}
}

func (m *GreetedEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GreetedEvent.Unmarshal(m, b)
}
func (m *GreetedEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GreetedEvent.Marshal(b, m, deterministic)
}
func (m *GreetedEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GreetedEvent.Merge(m, src)
}
func (m *GreetedEvent) XXX_Size() int {
	return xxx_messageInfo_GreetedEvent.Size(m)
}
func (m *GreetedEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_GreetedEvent.DiscardUnknown(m)
}

var xxx_messageInfo_GreetedEvent proto.InternalMessageInfo

func (m *GreetedEvent) GetMessage() *Greeting {
	if m != nil {
		return m.Message
	}
	return nil
}

func init() {
	proto.RegisterType((*Greeting)(nil), "org.leialearns.grpc.example.Greeting")
	proto.RegisterType((*Acknowledgement)(nil), "org.leialearns.grpc.example.Acknowledgement")
	proto.RegisterType((*GreetCommand)(nil), "org.leialearns.grpc.example.GreetCommand")
	proto.RegisterType((*GreetedEvent)(nil), "org.leialearns.grpc.example.GreetedEvent")
}

func init() {
	proto.RegisterFile("example.proto", fileDescriptor_15a1dc8d40dadaa6)
}

var fileDescriptor_15a1dc8d40dadaa6 = []byte{
	// 244 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x91, 0x4b, 0x4b, 0xc4, 0x30,
	0x14, 0x46, 0xad, 0xe0, 0x2b, 0xbe, 0x20, 0x8a, 0x0c, 0xba, 0x19, 0x8a, 0xc2, 0x80, 0x92, 0xca,
	0xf8, 0x03, 0x06, 0x15, 0x11, 0x57, 0x82, 0xee, 0x5c, 0x08, 0xb1, 0xfd, 0xbc, 0x84, 0x69, 0x1e,
	0xdc, 0x86, 0xd1, 0xad, 0xff, 0x5c, 0xa6, 0x66, 0x28, 0x8a, 0x14, 0x5d, 0x26, 0x39, 0x39, 0x9c,
	0x9b, 0x88, 0x6d, 0xbc, 0x6b, 0x1b, 0x6a, 0xa8, 0xc0, 0x3e, 0x7a, 0x79, 0xe4, 0x99, 0x54, 0x0d,
	0xa3, 0x6b, 0x68, 0x76, 0x8d, 0x22, 0x0e, 0xa5, 0x4a, 0x48, 0x7e, 0x2c, 0xd6, 0x6f, 0x19, 0x88,
	0xc6, 0x91, 0x1c, 0x88, 0x35, 0x8b, 0xa6, 0xd1, 0x84, 0x41, 0x36, 0xcc, 0x46, 0x1b, 0x0f, 0x8b,
	0x65, 0x7e, 0x2a, 0x76, 0x2f, 0xcb, 0xa9, 0xf3, 0x6f, 0x35, 0x2a, 0x82, 0x85, 0x8b, 0x3d, 0xf0,
	0x47, 0x26, 0xb6, 0x5a, 0xe7, 0xb5, 0xb7, 0x56, 0xbb, 0x4a, 0x9e, 0x8b, 0x3d, 0x4d, 0xc4, 0x20,
	0x1d, 0x71, 0x57, 0xc1, 0x45, 0xf3, 0x6a, 0xc0, 0xe9, 0xda, 0x6f, 0x47, 0x72, 0xd2, 0xc9, 0x97,
	0x87, 0xd9, 0x68, 0x73, 0x7c, 0xa2, 0x7a, 0x86, 0x50, 0x8b, 0x09, 0xba, 0x86, 0xfb, 0x94, 0x80,
	0xea, 0x66, 0x36, 0xaf, 0x9d, 0x7c, 0xaf, 0xfd, 0xb7, 0x70, 0x1c, 0xc4, 0xce, 0x97, 0x90, 0x1f,
	0xc1, 0x33, 0x53, 0x42, 0x3e, 0x8b, 0x95, 0x76, 0x47, 0xfe, 0x4d, 0x75, 0x78, 0xd6, 0x8b, 0xfd,
	0x78, 0xde, 0x7c, 0xe9, 0xea, 0xe0, 0x69, 0xbf, 0xe1, 0xb2, 0x08, 0x53, 0x2a, 0xe6, 0x64, 0x91,
	0xc8, 0x97, 0xd5, 0xf6, 0x57, 0x2f, 0x3e, 0x03, 0x00, 0x00, 0xff, 0xff, 0xd1, 0xd0, 0xfe, 0x6f,
	0xe6, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// GreeterServiceClient is the client API for GreeterService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GreeterServiceClient interface {
	// Greets AxonServer.
	Greet(ctx context.Context, in *Greeting, opts ...grpc.CallOption) (*Acknowledgement, error)
}

type greeterServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGreeterServiceClient(cc grpc.ClientConnInterface) GreeterServiceClient {
	return &greeterServiceClient{cc}
}

func (c *greeterServiceClient) Greet(ctx context.Context, in *Greeting, opts ...grpc.CallOption) (*Acknowledgement, error) {
	out := new(Acknowledgement)
	err := c.cc.Invoke(ctx, "/org.leialearns.grpc.example.GreeterService/Greet", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GreeterServiceServer is the server API for GreeterService service.
type GreeterServiceServer interface {
	// Greets AxonServer.
	Greet(context.Context, *Greeting) (*Acknowledgement, error)
}

// UnimplementedGreeterServiceServer can be embedded to have forward compatible implementations.
type UnimplementedGreeterServiceServer struct {
}

func (*UnimplementedGreeterServiceServer) Greet(ctx context.Context, req *Greeting) (*Acknowledgement, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Greet not implemented")
}

func RegisterGreeterServiceServer(s *grpc.Server, srv GreeterServiceServer) {
	s.RegisterService(&_GreeterService_serviceDesc, srv)
}

func _GreeterService_Greet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Greeting)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreeterServiceServer).Greet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/org.leialearns.grpc.example.GreeterService/Greet",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreeterServiceServer).Greet(ctx, req.(*Greeting))
	}
	return interceptor(ctx, in, info, handler)
}

var _GreeterService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "org.leialearns.grpc.example.GreeterService",
	HandlerType: (*GreeterServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Greet",
			Handler:    _GreeterService_Greet_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "example.proto",
}
